.github/workflows/npm-publish.yml
package-lock.json
package.json

I was setting git config after running npm version.  Since npm version commits a tag the git config needs to be before.
@sumitsuthar this workflow both versions package based on the semver release type you choose(patch, minor, major) and then also publishes and pushes tags.  What that means is you should never have to manually edit package.json/package-lock.json with a new version this workflow will handle it.

Fixed npm publish workflow

---

lib/nr-security-agent/index.js
lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js
lib/nr-security-api/index.js
package.json

Changed default fuzzing to localhost instead of 127.0.0.1

Fix for IAST scanning  in node 18

---

.github/workflows/npm-publish.yml
package-lock.json
package.json

I noticed that the package.json and package-lock.json was out of sync. This is because the release workflow was only pushing tags not the changes made when it runs npm version. This will fix this and get package.json and package-lock.json in sync.

fix: updated npm-publish workflow to use `--follow-tags` which will push the branch and tags made

---

README.md

I'm not sure how this repo was allowed to be made public without the OpenSource badge.  I added and included status badges for npm and the CI main.

fix: added open source badge and status badges to readme

---

.github/workflows/repolinter.yml

I noticed the repolinter is failing for 2 reasons.  One I cannot resolve as there needs to be some discuss topic in the forum but that's probably not necessary until GA. But the configuration was set for community not community plus, so I fixed that in this PR.

chore: updated repolinter config to use community-plus rulesets

---

.github/workflows/npm-publish.yml
.github/workflows/version-pkg.yml

This PR splits out versioning and publishing.  
The new workflow will be as follows:
* Run the Version Module workflow and pick the appropriate semver type.
* It will version the package
* Open PR with the package.json and package-lock changes
* Someone must review and merge PR
* Run the Publish module workflow
* This will publish the package
* Create a tag with the appropriate version and push tag to tip of main
You can see I tested this in my fork(commented out the publish) and all worked well: https://github.com/bizob2828/csec-node-agent/pull/4

ci: updated workflows to version and publish in separate workflows

---

lib/instrumentation-security/hooks/mysql/nr-mysql.js

I rebased the `k2-release` branch in agent which contained some mysql instrumentation fixes.  That uncovered the fact that both the agent and security agent instrumentation does not play nicely.  This PR fixes a few things:
* removes `shim.unwrap` as it no longer functions since you started using agent.
* replaces `shim.unwrap` with assigning symbols and checking those on whether or not to run instrumentation
* Makes the fix that causes this [error](https://github.com/newrelic/node-newrelic/actions/runs/5190976801/jobs/9358178905)

fix(mysql): fixed getConnection instrumentation to check if callback is wrapped or the "original" callback to avoid infinite wrapping

---

THIRD_PARTY_NOTICES.md
package-lock.json
package.json
third_party_manifest.json

The agent fails to install when `engine-strict=true `is provided to `npm install`. Latest version of check-disk-space module does not support Node.js v14. Downgraded dependency to its lower version which is compatible with Node.js v14.
Install agent with `engine-strict=true` flag
Closed #74

Fix(dep): pin check-disk-space to v3.3.1 to support Node.js v14

---

lib/nr-security-agent/lib/core/connections/websocket/response/IASTUtils.js

Set upper limit on IAST batch size to 40 to limit memory usage while IAST scan

perf: Fixed batch size threshold to 40

---

lib/nr-security-agent/index.js

When security.enabled flag is set to false. Do not apply instrumentation on modules.
Run application with security.enabled flag to false. 
Fixes [NR-150058](https://issues.newrelic.com/browse/NR-150058)

fix: Disable instrumentation when security enabled flag is set to false

---

README.md

Readme.md file updated for Node v20 and minor fix

chore: Readme update 

---

lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js
package-lock.json
package.json

1. Upgraded axios to 1.6.0 to resolve CVE-2023-45857.
2. Upgrade to latest version introduced regression in IAST fuzzing. Fixed the same by removing content-length header.
Fixes: [NR-174174](https://new-relic.atlassian.net/browse/NR-174174)

chore: Upgrade axios to 1.6.0 to resolve CVE-2023-45857

---

lib/nr-security-agent/lib/core/connections/websocket/websocket.js
package-lock.json
package.json

* Updated ws lib to v8.14.2.
* Updated intialization of websocket for v8.x
Run agent with Node.js application and check for websocket connectivity.
Fixes: [NR-175382](https://new-relic.atlassian.net/browse/NR-175382)

chore(dep): Upgraded ws to v8.14.2

---

lib/instrumentation-security/core/sec-utils.js
lib/nr-security-agent/lib/core/commonUtils.js
lib/nr-security-agent/lib/core/logging.js
lib/nr-security-agent/lib/core/statusUtils.js

Updated Permissions on files/directory created by security agent. Removed read, write and execute permissions for all users.
`npm run test`
Fixes [NR-201010](https://new-relic.atlassian.net/browse/NR-201010)

fix: Updated Permissions on files/directory created by security agent.

---

README.md

Added undici versions in readme and minor fixes.
```
npm run test
```
Fixes: [NR-235747](https://new-relic.atlassian.net/browse/NR-235747)

chore: Update readme for undici versions.

---

lib/instrumentation-security/core/request-manager.js
lib/instrumentation-security/core/sec-utils.js
lib/instrumentation-security/hooks/http/nr-http.js

* Implemented logic to truncate incoming http request for IAST processing.
* Added dataTruncated flag in event JSON.
* Default limit is 500KB
Fixes [NR-173806](https://new-relic.atlassian.net/issues/NR-173806)
[NR-173806]: https://new-relic.atlassian.net/browse/NR-173806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Functionality to truncate Incoming HTTP request upto default limit

---

lib/instrumentation-security/core/request-manager.js
lib/instrumentation-security/core/sec-utils.js
lib/instrumentation-security/hooks/director/nr-director.js
lib/instrumentation-security/hooks/express/nr-express.js
lib/instrumentation-security/hooks/fastify/nr-fastify.js
lib/instrumentation-security/hooks/grpc-js/nr-grpc.js
lib/instrumentation-security/hooks/hapi/nr-hapi.js
lib/instrumentation-security/hooks/http/nr-http.js
lib/instrumentation-security/hooks/koa/@koa/nr-@koa-router.js
lib/instrumentation-security/hooks/restify/nr-restify.js

We are doing work to remove the transaction from segment. I happen to find this when I was testing something else out.  This PR removes getting the transaction
from the segment and instead gets the transaction from the context manager by way of the tracer.
I didn't update any tests because they don't seem to be relevant but I'm more than happy to add any tests you see fit.
This PR should work now with any released agent but if this does not land before we release https://github.com/newrelic/node-newrelic/pull/2646 it will break the security agent.

chore: Updated instrumented to get the transaction directly instead of from the active segment

---

lib/instrumentation-security/hooks/fastify/nr-fastify.js

* Added Fix to detect fastify route.
* Updated logic to get route from fastify request's "Symbol(fastify.context)" field
`npm run test`
Fixes: [NR-336153](https://new-relic.atlassian.net/browse/NR-336153)
[NR-336153]: https://new-relic.atlassian.net/browse/NR-336153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix for empty route in fastify

---

lib/instrumentation-security/hooks/crypto/nr-crypto.js
lib/instrumentation-security/index.js
lib/nr-security-agent/lib/core/event.js

* Added instrumentation for crypto, hash and random.
`npm run test`

feat: Support  for Insecure settings i.e crypto, hash and random modules

---

lib/instrumentation-security/hooks/http/nr-http.js

This PR fixes an issue where the security agent adds the same listener many times which can result in a too many listeners error.

fix: Only listen once for uncaughtException
