lib/instrumentation-security/core/constants.js, lib/instrumentation-security/core/sec-trace.js, lib/instrumentation-security/core/sec-utils.js, lib/nr-security-agent/index.js, lib/nr-security-agent/lib/core/Policy.js, lib/nr-security-agent/lib/core/applicationinfo.js, lib/nr-security-agent/lib/core/commonUtils.js, lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js, lib/nr-security-agent/lib/core/logging.js, lib/nr-security-agent/lib/core/sec-agent-constants.js, lib/nr-security-agent/lib/core/statusUtils.js, lib/nr-security-agent/resources/config.js
- Handling to use OS specific path separator.
- Functionality to create directories in windows environment.
- IAST support for windows.
=> Windows support

CHANGELOG.md, package-lock.json, package.json
This reverts commit 00483d51ca40922f556639c93d1a8b53937fb5b6.
=> Revert "(#45)"

lib/nr-security-agent/index.js, lib/nr-security-agent/lib/core/agent-status.js, lib/nr-security-agent/lib/core/applicationinfo.js, lib/nr-security-agent/lib/core/commonUtils.js, lib/nr-security-agent/lib/core/connections/websocket/websocket.js, lib/nr-security-agent/lib/core/sec-util.js, lib/nr-security-agent/lib/core/statusUtils.js, lib/nr-security-agent/lib/core/websocket-client.js, package.json
- Fix for agent stats and websocket stats in snapshot file.
- Handshake timeout in websocket connection
=> Snapshot fix

index.js, lib/instrumentation-security/core/request-manager.js, lib/instrumentation-security/core/sec-utils.js, lib/instrumentation-security/hooks/http/nr-http.js, lib/nr-security-agent/index.js, lib/nr-security-agent/lib/core/sha-size-util.js
1. Fix for Fire and forget type of requests.
2. Handling for high_security flag.
3. Handling to save incoming http request data based on traceId in case activeSegment is null or transactionId is not mapped to trace.
=> Fix for NR-123832, Check for high_security flag

THIRD_PARTY_NOTICES.md, lib/nr-security-agent/lib/core/connections/websocket/websocket.js, package-lock.json, package.json, third_party_manifest.json
* Updated @aws-sdk/client-lambda to mitigate CVE.
* Minor fix in websocket reconnect
=> Fix: Vulnerability in fast-xml-parser 4.1.2. Updated @aws-sdk/client-lambda 

lib/instrumentation-security/hooks/http/nr-http.js
* Replaced executionId with event Id.
=> Fix: forwarded id in microservice IAST detection

lib/nr-security-agent/lib/core/connections/websocket/websocket.js
* Added WS logging 
* close callback added.
=> feat: ws close callback and minor logging

lib/instrumentation-security/hooks/fs/nr-fs.js, lib/instrumentation-security/hooks/mysql/nr-mysql.js
- Fix in params for mysql hook
- Fix in params for file hooks
=> Fix: Mysql param fix

.github/PULL_REQUEST_TEMPLATE.md
=> chore: Create PR template

package-lock.json, package.json
- upgrade semver from 7.5.3 to 7.5.4
- upgrade @aws-sdk/client-lambda from 3.348.0 to 3.363.0
=> chore(deps): Updated semver and @aws-sdk/client-lambda dependecies

lib/nr-security-agent/lib/core/connections/websocket/response/IASTUtils.js
Updated IAST batch processing threshold to 160
=> perf: Updated IAST processing batch size threshold

lib/instrumentation-security/hooks/http/nr-http.js, lib/nr-security-agent/lib/core/Auth-headers.js, lib/nr-security-agent/lib/core/commonUtils.js, lib/nr-security-agent/lib/core/logging.js, lib/nr-security-agent/lib/core/sec-agent-constants.js
While creating logger set default log level to info if random string is passed. Added logging for authentication headers.
Handling to write logs to stderr/stdout
Provide random string in log level and see the behaviour of agent.
Fixes: [NR-154505](https://issues.newrelic.com/browse/NR-154505)
=> Fix: Logging update for default log level and status file

.github/workflows/ci-workflow.yml
Updated CI to not run on Pull requests (temporary).
=> chore: CI update for PR

lib/instrumentation-security/index.js
Updated newrelic.instrument* APIs with isEsm: true flag.
=> fix: Added isEsm flag in instrumentation API

package-lock.json, package.json, test/instrumentation-security/grpc-js/greeter.proto, test/instrumentation-security/grpc-js/nr-grpc.test.js
Added unit tests for gRPC instrumentation
`npm run test`
=> test: gRPC unit test cases

package-lock.json, package.json, test/instrumentation-security/dynamodb/nr-dynamodb-v2.test.js, test/instrumentation-security/dynamodb/nr-dynamodb-v3.test.js, test/instrumentation-security/dynamodb/util.test.js
Added unit tests for Dynamodb v2 and v3 instrumentation
`npm run test`
=> test: DynamoDB unit test cases

package-lock.json, package.json, test/instrumentation-security/nr-cassandra-driver.test.js
Added unit tests for cassandra-driver instrumentation
`npm run test`
=> test: cassandra-driver unit tests cases

lib/nr-security-agent/lib/core/connections/websocket/websocket.js, lib/nr-security-agent/lib/core/sec-util.js, lib/nr-security-agent/lib/core/websocket-client.js
Implemented handling to add base event in raspEventstats. Now exitEventSentCount key is part of healthcheck  as well.
Check generated health check json for IAST scanning.
Fixes: [NR-168268](https://issues.newrelic.com/browse/NR-168268)
=> fix: event stats fixes in healthcheck json

.github/workflows/ci-workflow.yml
Added flag to skip CI based on should_skip flag
=> ci: should_skip flag added

test/instrumentation-security/grpc-js/nr-grpc.test.js
Added unit tests for gRPC instrumentation
`npm run test`
=> Grpc instrument tests

lib/instrumentation-security/hooks/grpc-js/nr-grpc.js, lib/nr-security-agent/lib/core/connections/grpcClient.js
Implemented handling to get service name and protofile definition from loadPackageDefinition hook.
Fixes: [NR-171187](https://new-relic.atlassian.net/browse/NR-171187)
=> feat: Functionality to get protofile definition.

THIRD_PARTY_NOTICES.md, package-lock.json, package.json, third_party_manifest.json
Updated dependencies for uuid and @aws-sdk/client-lambda
=> chore(deps): Updated dependencies for uuid and @aws-sdk/client-lambda 

.github/workflows/ci-workflow.yml
Update in CI workflow to remove Node v14. 
`npm run test`
=> ci: Unit test CI update

package-lock.json, package.json
Upgrade check-disk-space to latest version which is 3.4.0
Fixes: [NR-176039](https://new-relic.atlassian.net/browse/NR-176039)
=> chore(dep): Updated check-disk-space to  v3.4.0

lib/instrumentation-security/hooks/fs/nr-fs.js
Fix misspelled constant in fs.open() hook.
Fixes: [NR-177450](https://new-relic.atlassian.net/browse/NR-177450)
=> fix: Fixed misspelled constant in fs.open() hook.

lib/instrumentation-security/hooks/@nestjs/nr-nestjs-core.js, lib/instrumentation-security/index.js
Added instrumentation for @nestjs/core module.
Run agent with nestjs application and check generated events.
Fixes: [NR-174959](https://new-relic.atlassian.net/browse/NR-174959)
=> feat: Support for Nestjs framework

lib/nr-security-agent/lib/core/applicationinfo.js
* fixed setter for pod properties to set containerInfo.
Run agent in k8s and check applicationInfo json
Fixes: [NR-180664](https://new-relic.atlassian.net/browse/NR-180664)
=> fix: Fix in applicationInfo for pod properties

package-lock.json
Updated lockfileVersion to 2 in package-lock.json
`npm run test`
Fixes: [NR-181769](https://new-relic.atlassian.net/browse/NR-181769)
=> chore: Update in lockfileVersion of package-lock.json

lib/instrumentation-security/hooks/memcached/nr-memcached.js, test/instrumentation-security/nr-memcached.test.js
* Updated security event schema for memcached.
* Added mode, and type for parameters.
* Updated Uts
`npm run test`
Fixes: [NR-182099](https://new-relic.atlassian.net/browse/NR-182099)
=> fix: Memcached event schema update

lib/instrumentation-security/hooks/@nestjs/nr-nestjs-core.js, lib/instrumentation-security/hooks/express/nr-express.js, lib/instrumentation-security/hooks/fastify/nr-fastify.js, lib/instrumentation-security/hooks/fs/nr-fs.js, lib/instrumentation-security/hooks/hapi/nr-hapi.js, lib/instrumentation-security/hooks/http/nr-http.js, lib/instrumentation-security/hooks/koa/@koa/nr-@koa-router.js, lib/instrumentation-security/hooks/ldap/nr-ldap.js, lib/instrumentation-security/hooks/mongodb/common.js, lib/instrumentation-security/hooks/mongodb/nr-mongodb.js, lib/instrumentation-security/hooks/mysql/nr-mysql.js, lib/instrumentation-security/hooks/native/nr-childProcess.js, lib/instrumentation-security/hooks/postgres/nr-postgres.js, lib/instrumentation-security/hooks/restify/nr-restify.js, lib/instrumentation-security/hooks/xpath/nr-xpath.js
* Added debug logs for all the modules and its methods which are instrumented.
Run agent with debug/trace logging.
Fixes: [NR-182517](https://new-relic.atlassian.net/browse/NR-182517)
=> chore: Additional logging for instrumented modules and methods

lib/nr-security-agent/lib/core/Auth-headers.js
Added NR-CSEC-ENTITY-GUID and NR-CSEC-ENTITY-NAME in ws headers
Fixes: [NR-170125](https://new-relic.atlassian.net/browse/NR-170125)
=> feat: Add ws headers NR-CSEC-ENTITY-GUID and NR-CSEC-ENTITY-NAME 

package-lock.json, package.json, test/instrumentation-security/nr-undici.test.js
Added unit tests for undici instrumentation
`npm run test`
=> Undici test

package-lock.json, package.json, test/instrumentation-security/nr-@elastic.test.js
Added unit tests for elasticsearch instrumentation
`npm run test`
=> added elastic_search test

package.json
Added NR-CSEC-ENTITY-GUID & NR-CSEC-ENTITY-NAME in ws headers that's why we have to update jsonVersion to 1.1.1.
Fixes: [NR-187529](https://new-relic.atlassian.net/browse/NR-187529)
=> fix: update jsonVersion to 1.1.1 due to additional headers in ws connection.

lib/instrumentation-security/core/sec-utils.js, lib/instrumentation-security/hooks/http/nr-http.js
* Added missing protocol in incoming http request object.
* Added asserts for function hooks
Fixes [NR-189949](https://new-relic.atlassian.net/browse/NR-189949)
=> fix: Added missing protocol in incoming http request object

lib/nr-security-agent/index.js
Added informative log messages regarding start of Security agent to APM logs.
Check logs of APM agent. eg.
`{"v":0,"level":30,"name":"newrelic","hostname":"hostname","pid":10721,"time":"2023-12-14T05:38:55.187Z","msg":"Starting New Relic Node.js Security Agent ","component":"security-agent","module":"NewRelicAPI"}`
Closes: #[NR-191072](https://new-relic.atlassian.net/browse/NR-191072)
=> chore: Added informative log messages to APM logs.

lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js
Added handling to honour probing interval from policy for iast-data-request.
Fixes: [NR-187526](https://new-relic.atlassian.net/browse/NR-187526)
=> fix: honouring probing interval from policy

package-lock.json, package.json
Updated axios to v1.6.3
`npm run test`
=> chore(deps): Update axios to v1.6.3

lib/nr-security-agent/lib/core/Auth-headers.js, lib/nr-security-agent/lib/core/LogMessage.js, lib/nr-security-agent/lib/core/commonUtils.js, lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js, lib/nr-security-agent/lib/core/connections/websocket/response/index.js, lib/nr-security-agent/lib/core/connections/websocket/websocket.js, lib/nr-security-agent/lib/core/sec-agent-constants.js, lib/nr-security-agent/lib/core/sec-util.js, lib/nr-security-agent/lib/core/websocket-client.js
Handling to send important logs/errors via websocket to security engine.
Fixes [NR-163716](https://new-relic.atlassian.net/issues/NR-163716)
=> feat: Support to send important log/errors to security engine

THIRD_PARTY_NOTICES.md, lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js, package-lock.json, package.json, third_party_manifest.json
Removed pinned version for axios and check-disk-space
`npm run test`
=> chore(deps): Removed pinned version for axios and check-disk-space

lib/instrumentation-security/hooks/http/nr-http.js
Added handling to exclude unsupported response content types from reflected xss processing.
Fixes [#163712](https://new-relic.atlassian.net/browse/NR-163712)
=> feat: Handling to exclude unsupported content types from rxss processing

lib/nr-security-agent/lib/core/connections/aws-lambda-client.js, package-lock.json, package.json
Removed dependency of @aws-sdk/client-lambda
`npm run test`
Closes #159
=> fix: removed dependency @aws-sdk/client-lambda

lib/nr-security-agent/lib/core/LogMessage.js
Updated log event  json name to "critical-messages".
Enable IAST agent and check for log message JSON.
Fixes[ NR-213420](https://new-relic.atlassian.net/browse/NR-213420)
=> fix: Update json name for log event to "critical-messages"

lib/nr-security-agent/lib/core/LogMessage.js, lib/nr-security-agent/lib/core/commonUtils.js, lib/nr-security-agent/lib/core/statusUtils.js
Handling to report errors in directory creation and snapshot file. Added handling to send pid in critical-messages json.
`npm run test`
Fixes [NR-214357](https://new-relic.atlassian.net/browse/NR-214357)
=> feat : Handling to report errors in directory creation and snapshot file

lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js, lib/nr-security-agent/lib/core/connections/websocket/response/index.js
* Fixed import of commonUtils module
* Fix for ReferenceError of commonUtils module 
`npm run test`
Fixes: [NR-215398](https://new-relic.atlassian.net/browse/NR-215398)
=> fix: Fix for ReferenceError of commonUtils module 

lib/nr-security-agent/lib/core/event.js
Node.js Security agent should report framework in security event json
`npm run test`
Fixes: [NR-217246](https://new-relic.atlassian.net/browse/NR-217246)
=> fix: Reporting of framework in security event json

lib/nr-security-agent/lib/core/connections/websocket/response/startup-handshake-handler.js
Added handling  to send critical messages on successful startup of agent when agent is successfully connected to Security Engine and fully functioning.
`npm run test`
Fixes: [NR-217861](https://new-relic.atlassian.net/browse/NR-217861)
=> chore: Ability to send critical messages on successful startup of agent.

LICENSE, package.json
* Update software license to New Relic Software License Version 1.0
`npm run test`
Closes:[NR-219872](https://new-relic.atlassian.net/browse/NR-219872)
=> chore: Update software license to New Relic Software License Version 1.0

README.md
Updated license in readme
`npm run test`
=> chore: Updated license in readme

README.md
* Updated readme file for grpc versions.
`npm run test`
=> chore: Readme update

package-lock.json, package.json
Updated axios to latest version v1.6.8
`npm run test`
Fixes: [NR-249809](https://new-relic.atlassian.net/browse/NR-249809)
[NR-249809]: https://new-relic.atlassian.net/browse/NR-249809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(deps): Updated axios to v1.6.8

lib/instrumentation-security/hooks/express/nr-express.js
* Added instrumentation for express framework's res.download() and res.sendFile() to detect file access vulnerability.
`npm run test`
Fixes: [NR-254191](https://new-relic.atlassian.net/browse/NR-254191)
[NR-254191]: https://new-relic.atlassian.net/browse/NR-254191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Added instrumentation for express framework's res.download() and res.sendFile()

lib/nr-security-agent/lib/core/Policy.js, lib/nr-security-agent/lib/core/commonUtils.js, lib/nr-security-agent/lib/core/sec-agent-constants.js, lib/nr-security-agent/lib/core/statusUtils.js
* Fixed minor issue related to empty framework, additional colon, and name update.
* Now snapshot file will have application framework filled.
* SEC_HOME to CSEC_HOME
* Removed additional colon.
`npm run test`
Fixes: [NR-248864](https://new-relic.atlassian.net/browse/NR-248864)
[NR-248864]: https://new-relic.atlassian.net/browse/NR-248864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: logging and snapshot file fixes

lib/nr-security-agent/lib/core/sec-agent-constants.js, lib/nr-security-agent/lib/core/sec-util.js
* Added handling to prepend vulnerability case type with apiId
`npm run test`
Fixes: [NR-257567](https://new-relic.atlassian.net/browse/NR-257567)
[NR-257567]: https://new-relic.atlassian.net/browse/NR-257567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Prepend vulnerability case type with apiId

lib/nr-security-agent/lib/core/xss-utils.js
*  Added assert for type of response data in Reflected XSS validation
`npm run test`
Fixes: [NR-261509](https://new-relic.atlassian.net/browse/NR-261509)
[NR-261509]: https://new-relic.atlassian.net/browse/NR-261509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Added assert for typeof response data in Reflected XSS validation

lib/nr-security-agent/lib/core/connections/websocket/response/IASTUtils.js, lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js, lib/nr-security-agent/lib/core/connections/websocket/websocket.js
* Issue with control commands acknowledgement on Security Agent side.
* Added handling to reconnect only when websocket state is closing or closed.
`npm run test`
Fixes: [NR-259500](https://new-relic.atlassian.net/browse/NR-259500)
[NR-259500]: https://new-relic.atlassian.net/browse/NR-259500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Fix for control commands acknowledgement in security agent.

lib/nr-security-agent/lib/core/commonUtils.js, lib/nr-security-agent/lib/core/connections/websocket/response/startup-handshake-handler.js, lib/nr-security-agent/lib/core/statusUtils.js, lib/nr-security-agent/lib/core/websocket-client.js
* Updated log level for critical messages
`npm run test`
Fixes: [NR-249820](https://new-relic.atlassian.net/browse/NR-249820)
[NR-249820]: https://new-relic.atlassian.net/browse/NR-249820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Updated log level for critical messages

lib/nr-security-agent/lib/core/sec-util.js
* Added route field in http request object for API endpoint mapping
`npm run test`
Closes: [NR-267563](https://new-relic.atlassian.net/browse/NR-267563)
[NR-267563]: https://new-relic.atlassian.net/browse/NR-267563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Added route field in security event for API endpoint mapping

lib/instrumentation-security/core/security-metadata.js
* Added logic to convert all the http header values into string data type.
`npm run test`
Closes: [NR-270740](https://new-relic.atlassian.net/browse/NR-270740)
[NR-270740]: https://new-relic.atlassian.net/browse/NR-270740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Handling to convert header values into string

package-lock.json, package.json
Updated package.json to bump ws from 8.14.2 to 8.17.1
=> chore(deps): Updated package.json to bump ws from 8.14.2 to 8.17.1 

lib/instrumentation-security/core/constants.js, lib/instrumentation-security/hooks/grpc-js/nr-grpc.js
* Implementation to detect and generate API endpoints. 
`npm run test`
Closes: [NR-254194](https://new-relic.atlassian.net/browse/NR-254194)
[NR-254194]: https://new-relic.atlassian.net/browse/NR-254194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Support to detect gRPC API endpoints

lib/nr-security-agent/lib/core/connections/restclient.js
* Remove additional headers added by IAST client while fuzzing.
`npm run test`
Fixes: [NR-263236](https://new-relic.atlassian.net/browse/NR-263236)
[NR-263236]: https://new-relic.atlassian.net/browse/NR-263236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove additional headers added by IAST client

lib/instrumentation-security/hooks/http/nr-http.js
* Updated from timer based implementation.
`npm run test`
=> fix: Fix for uncaught exception reporting

.github/workflows/ci-workflow.yml
* Added handling to run instrumentation unit tests on node v22.x
`npm run test`
Closes: [NR-287275](https://new-relic.atlassian.net/browse/NR-287275)
[NR-287275]: https://new-relic.atlassian.net/browse/NR-287275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: Added node v22.x to unit tests

package-lock.json, package.json
* Bumped axios from 1.6.8 to 1.7.4. 
* Fix for CVE-2024-39338
`npm run test`
Closes: #242
=> chore(deps): bumped axios from 1.6.8 to 1.7.4

lib/nr-security-agent/lib/core/ExceptionReporting.js
* Added asserts for traceId in error reporting data generation.
`npm run test`
Closes: [NR-295949](https://new-relic.atlassian.net/browse/NR-295949)
[NR-295949]: https://new-relic.atlassian.net/browse/NR-295949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Fix for traceId in error reporting

lib/nr-security-agent/lib/core/connections/websocket/response/IASTUtils.js, lib/nr-security-agent/lib/core/websocket-client.js
* fix for missing identifiers in iast-data-request JSON
`npm run test`
Fixes: [NR-315271](https://new-relic.atlassian.net/browse/NR-315271)
[NR-315271]: https://new-relic.atlassian.net/browse/NR-315271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: fix for missing identifiers in iast-data-request JSON

lib/instrumentation-security/hooks/fs/nr-fs.js
* Handling to not resolve file path in fs module instrumentation
`npm run test`
Fixes: [NR-316055](https://new-relic.atlassian.net/browse/NR-316055)
[NR-316055]: https://new-relic.atlassian.net/browse/NR-316055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Handling to not resolve file path in fs module instrumentation

lib/nr-security-agent/lib/core/connections/websocket/response/IASTUtils.js, lib/nr-security-agent/lib/core/connections/websocket/response/fuzz-request-handler.js
* Updated batch size.
* Updated logic to send iast-data-request on basis of last fuzz request time.
`npm run test`
Fixes: [NR-336638](https://new-relic.atlassian.net/browse/NR-336638)
[NR-336638]: https://new-relic.atlassian.net/browse/NR-336638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Fix for batch size and condition of iast-data-request sending

lib/nr-security-agent/lib/core/health-check.js
* Fix for assignment to logger constant
Fixes: #265
=> fix: Fix for assignment to logger constant

lib/instrumentation-security/hooks/express/nr-express.js, lib/instrumentation-security/index.js
* Support for express 5.x
`npm run test`
Closes: [NR-319862](https://new-relic.atlassian.net/browse/NR-319862)
[NR-319862]: https://new-relic.atlassian.net/browse/NR-319862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Support for express 5.x

lib/instrumentation-security/index.js
* APM versioned test is failing due to instrumentation of crypto hash and random instrumentation. Need to update the metric counts for versioned tests.
=> rev: Reverted changes of PR#185

lib/instrumentation-security/hooks/graphql/nr-graphql.js
* Fix to get transaction in graphql instrumentation.
* Update logic to get transaction object from tracer instead of segment
```
npm run test
```
=> fix: Fix for getting transaction in graphql instrumentation

package-lock.json, package.json
* Updated axios to v1.7.9
`npm run test`
Closes: [NR-355131](https://new-relic.atlassian.net/browse/NR-355131)
[NR-355131]: https://new-relic.atlassian.net/browse/NR-355131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(deps): Updated axios to v1.7.9

lib/instrumentation-security/hooks/crypto/nr-crypto.js
* Fix for TypeError while getting includes in nr-crypto.js
* Rerun a regression
=> fix: crypto-error fix

lib/nr-security-agent/lib/core/sec-util.js
* Added safety check for agentModule before accessing its properties
```
npm run test
```
Fixes: [NR-365300](https://new-relic.atlassian.net/browse/NR-365300)
[NR-365300]: https://new-relic.atlassian.net/browse/NR-365300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Added safety check for agentModule before accessing its properties

package-lock.json, package.json, test/instrumentation-security/nr-mongodb.test.js
*  Removed docker-cli-js dependency and updated mongodb unit test case
```
npm run test
```
Issue #282
=> fix: Removed docker-cli-js dependency and updated mongodb unit test case

package-lock.json, package.json
=> chore(deps): Updated axios to v1.8.4

THIRD_PARTY_NOTICES.md, lib/nr-security-agent/lib/core/applicationinfo.js, package-lock.json, package.json, third_party_manifest.json
*  Removed dependency sync-req and updated axios
```
npm run test
```
Fixes #304
=> fix: Removed dependency sync-req and updated axios
